// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-QkFB814W8yi_0O1j5Ad_e0br8Vm5O8',
    appId: '1:500636035712:web:acd8feccb24ea7b327d465',
    messagingSenderId: '500636035712',
    projectId: 'memory-game-989b6',
    authDomain: 'memory-game-989b6.firebaseapp.com',
    storageBucket: 'memory-game-989b6.firebasestorage.app',
    measurementId: 'G-VTVQHSZKQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsC9F0zuosqG3_ysLkAoNWl8GQcu4aaR4',
    appId: '1:500636035712:android:b99f7bd849f5b47a27d465',
    messagingSenderId: '500636035712',
    projectId: 'memory-game-989b6',
    storageBucket: 'memory-game-989b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTH2OxEo3bFttlaVZayExdG_jnUzGNmVM',
    appId: '1:500636035712:ios:2dac9370e30ba69f27d465',
    messagingSenderId: '500636035712',
    projectId: 'memory-game-989b6',
    storageBucket: 'memory-game-989b6.firebasestorage.app',
    iosBundleId: 'com.example.memoryGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTH2OxEo3bFttlaVZayExdG_jnUzGNmVM',
    appId: '1:500636035712:ios:2dac9370e30ba69f27d465',
    messagingSenderId: '500636035712',
    projectId: 'memory-game-989b6',
    storageBucket: 'memory-game-989b6.firebasestorage.app',
    iosBundleId: 'com.example.memoryGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU-QkFB814W8yi_0O1j5Ad_e0br8Vm5O8',
    appId: '1:500636035712:web:9c547085f0d9995b27d465',
    messagingSenderId: '500636035712',
    projectId: 'memory-game-989b6',
    authDomain: 'memory-game-989b6.firebaseapp.com',
    storageBucket: 'memory-game-989b6.firebasestorage.app',
    measurementId: 'G-83T7NTBFTT',
  );
}
